package(default_visibility = ["//roman:internal"])

#cc_library(
#    name = "errors",
#    srcs = ["errors.cc"],
#    hdrs = ["errors.h"],
#    deps = [
#        "@glib//:glib"
#    ],
#)

#cc_library(
#    name = "glib",
#    hdrs = ["glib.h"],
#    srcs = ["glib.cc"],
#    deps = [
#        "@absl//absl/memory",
#        "@glib//:glib",
#    ],
#)

cc_library(
    name = "strings",
    hdrs = ["strings.h"],
    deps = [
        "@absl//absl/types:span",
    ],
)
